version: "3.9"
services:
  employee-tracker:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: employee-tracker
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_USER: employee-tracker-user
      MYSQL_PASSWORD: password123
    volumes:
      - ../../data/mysql:/var/lib/mysql
